-- Farblich passende Platzhalterbilder "FOTO FOLGT" je Produkt (Stand 2026-10-10).
-- Zuordnung nach Produktname, Sorte und allgemein bekannter Dosenfarbe, ohne Abruf fremder
-- Webseiten oder Bilder. Unbekannte Produkte behalten den blauen CanSpot-Platzhalter.
-- Produkte mit eigenem Foto (Red Bull White Peach Sugarfree, Monster Juiced Bad Apple) bleiben unverändert.
-- Bilder: https://canspot.de/wp-content/Produktbilder/platzhalter-foto-folgt/

begin;

with zuordnung(marke, produkt, farbe) as (values
  ('28 Black', '28 Black Açaí', 'purpur'),
  ('28 Black', '28 Black Açaí Zero', 'violett'),
  ('28 Black', '28 Black Limette-Minze', 'hellgruen'),
  ('28 Black', '28 Black Sour Mango-Kiwi', 'gelbgruen'),
  ('Action', 'Action Energy Green Apple', 'hellgruen'),
  ('Bang', 'Bang Peach Mango', 'gelborange'),
  ('Booster Energy', 'Booster Absolute Zero', 'weiss'),
  ('Booster Energy', 'Booster Blue Bomb Blueberry', 'blau'),
  ('Booster Energy', 'Booster Citrus', 'gelb'),
  ('Booster Energy', 'Booster Exotic', 'rotorange'),
  ('Booster Energy', 'Booster Hemp', 'gruen'),
  ('Booster Energy', 'Booster Juicy', 'magenta'),
  ('Booster Energy', 'Booster Original', 'blau'),
  ('C4 Energy', 'C4 Energy Frozen Bombsicle Zero', 'himmelblau'),
  ('Crazy Wolf', 'Crazy Wolf Cranberry Chili', 'karmin'),
  ('Crazy Wolf', 'Crazy Wolf Energy Drink', 'schwarz'),
  ('Crazy Wolf', 'Crazy Wolf Ginseng + Guarana', 'gruen'),
  ('Effect', 'Effect BCAA Energy Tropical Blast', 'gelborange'),
  ('Effect', 'Effect Black Açaí', 'purpur'),
  ('Effect', 'Effect Bubble Gum', 'magenta'),
  ('Effect', 'Effect Energy Drink', 'schwarz'),
  ('Effect', 'Effect Performance Super Berry', 'violett'),
  ('Effect', 'Effect Shredded Cola Crush', 'rot'),
  ('Effect', 'Effect Zero', 'weiss'),
  ('Flying Power', 'Flying Power Apple Cinnamon', 'rotorange'),
  ('Flying Power', 'Flying Power Cherry Vanilla', 'karmin'),
  ('Flying Power', 'Flying Power Energy Drink', 'blau'),
  ('Flying Power', 'Flying Power Guave', 'magenta'),
  ('Flying Power', 'Flying Power Lotus Karamell', 'gelborange'),
  ('Flying Power', 'Flying Power Raspberry Strike', 'magenta'),
  ('Flying Power', 'Flying Power Sauerkirsche', 'rot'),
  ('Flying Power', 'Flying Power Think Big Heidelbeere-Kaktusfeige', 'violett'),
  ('Flying Power', 'Flying Power Think Big Orange-Yuzu', 'gelborange'),
  ('Flying Power', 'Flying Power Watermelon', 'rot'),
  ('Flying Power', 'Flying Power Zero', 'weiss'),
  ('Gönrgy', 'Gönrgy Juneberry Jam', 'violett'),
  ('Gönrgy', 'Gönrgy No Winter Edition Tropical Guave', 'magenta'),
  ('Gönrgy', 'Gönrgy Raspberry Cheesecake', 'karmin'),
  ('Gönrgy', 'Gönrgy Sweet Lemon', 'gelb'),
  ('Gönrgy', 'Gönrgy Tropical Exotic', 'gelborange'),
  ('Gönrgy', 'Gönrgy White Peach', 'weiss'),
  ('Kong Strong', 'Kong Strong Cold Brew Coffee', 'rotorange'),
  ('Kong Strong', 'Kong Strong Colossus', 'schwarz'),
  ('Kong Strong', 'Kong Strong Colossus Zero', 'weiss'),
  ('Kong Strong', 'Kong Strong Energy Drink', 'schwarz'),
  ('Kong Strong', 'Kong Strong Hanf', 'gruen'),
  ('Kong Strong', 'Kong Strong Kokos-Blaubeere', 'blau'),
  ('Kong Strong', 'Kong Strong Sugar Free', 'himmelblau'),
  ('Kong Strong', 'Kong Strong Sugar Free XXL', 'himmelblau'),
  ('Kong Strong', 'Kong Strong Wild Power', 'rot'),
  ('Monster Energy', 'Espresso Monster', 'rotorange'),
  ('Monster Energy', 'Monster Energy Absolutely Zero', 'schwarz'),
  ('Monster Energy', 'Monster Energy Assault', 'schwarz'),
  ('Monster Energy', 'Monster Energy Classic', 'gruen'),
  ('Monster Energy', 'Monster Energy Juiced Aussie Style Lemonade', 'gelb'),
  ('Monster Energy', 'Monster Energy Juiced Khaotic', 'gelborange'),
  ('Monster Energy', 'Monster Energy Juiced Mixxd Punch', 'purpur'),
  ('Monster Energy', 'Monster Energy Juiced Monarch', 'rotorange'),
  ('Monster Energy', 'Monster Energy Lewis Hamilton Zero Sugar', 'violett'),
  ('Monster Energy', 'Monster Energy Nitro', 'schwarz'),
  ('Monster Energy', 'Monster Energy Reserve Watermelon', 'rot'),
  ('Monster Energy', 'Monster Energy The Doctor', 'gelbgruen'),
  ('Monster Energy', 'Monster Energy Ultra', 'weiss'),
  ('Monster Energy', 'Monster Energy Ultra Fiesta Mango', 'gelborange'),
  ('Monster Energy', 'Monster Energy Ultra Paradise', 'hellgruen'),
  ('Monster Energy', 'Monster Energy Ultra Red', 'rot'),
  ('Monster Energy', 'Monster Energy Ultra Rosá', 'magenta'),
  ('Monster Energy', 'Monster Energy Ultra Violet', 'violett'),
  ('Monster Energy', 'Monster Energy Ultra Watermelon', 'karmin'),
  ('Monster Energy', 'Monster Rehab Peach Tea', 'rotorange'),
  ('NOCCO', 'NOCCO Miami Strawberry', 'karmin'),
  ('Red Bull', 'Red Bull Açaí', 'purpur'),
  ('Red Bull', 'Red Bull Energy Drink', 'blau'),
  ('Red Bull', 'Red Bull Feige-Apfel', 'hellgruen'),
  ('Red Bull', 'Red Bull Green Edition', 'gruen'),
  ('Red Bull', 'Red Bull Iced Vanilla Berry', 'himmelblau'),
  ('Red Bull', 'Red Bull Juneberry', 'purpur'),
  ('Red Bull', 'Red Bull Kokos-Blaubeere', 'weiss'),
  ('Red Bull', 'Red Bull Pfirsich', 'rotorange'),
  ('Red Bull', 'Red Bull Red Edition', 'rot'),
  ('Red Bull', 'Red Bull Sugarfree', 'himmelblau'),
  ('Red Bull', 'Red Bull Summer Edition Drachenfrucht', 'magenta'),
  ('Red Bull', 'Red Bull Tropical', 'gelb'),
  ('Red Bull', 'Red Bull Winter Edition Granatapfel', 'karmin'),
  ('Red Bull', 'Red Bull Zero', 'tuerkis'),
  ('Reign', 'Reign Sour Apple', 'hellgruen'),
  ('Rockstar Energy', 'Rockstar Apple', 'gelbgruen'),
  ('Rockstar Energy', 'Rockstar Berry Blast', 'violett'),
  ('Rockstar Energy', 'Rockstar Blueberry Pomegranate Açaí', 'purpur'),
  ('Rockstar Energy', 'Rockstar Freeze', 'himmelblau'),
  ('Rockstar Energy', 'Rockstar Frozen Raspberry', 'magenta'),
  ('Rockstar Energy', 'Rockstar Guava Pineapple', 'gelb'),
  ('Rockstar Energy', 'Rockstar Juiced El Mango', 'gelborange'),
  ('Rockstar Energy', 'Rockstar Juiced Machu Peachu', 'rotorange'),
  ('Rockstar Energy', 'Rockstar Mixed Berries', 'violett'),
  ('Rockstar Energy', 'Rockstar Organic Island Fruit', 'tuerkis'),
  ('Rockstar Energy', 'Rockstar Organic Strawberry', 'rot'),
  ('Rockstar Energy', 'Rockstar Original', 'schwarz'),
  ('Rockstar Energy', 'Rockstar Pineapple & Coconut', 'gelb'),
  ('Rockstar Energy', 'Rockstar Revolt Killer Cherry', 'karmin'),
  ('Rockstar Energy', 'Rockstar Sour Raspberry', 'magenta'),
  ('Rockstar Energy', 'Rockstar Waldmeister', 'gruen'),
  ('Rockstar Energy', 'Rockstar XDurance Grape', 'purpur'),
  ('Vita Energy', 'Vita Energy Himbeere-Wassermelone Zero', 'karmin'),
  ('Vita Energy', 'Vita Energy Mango-Orange', 'gelborange')
)
update products p
   set image_url = 'https://canspot.de/wp-content/Produktbilder/platzhalter-foto-folgt/platzhalter-foto-folgt-'
                   || z.farbe || '-450x600.webp',
       image_is_example = false
  from zuordnung z, brands b
 where b.id = p.brand_id
   and b.name = z.marke
   and p.name = z.produkt;

-- Kontrolle: Verteilung der Bilder
select regexp_replace(image_url, '^.*/', '') as bild, count(*)
  from products group by 1 order by 2 desc;

commit;
